# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##########################################################################################
# Be sure to edit the values below
##########################################################################################

title: CDC COVID-19 Answers
logo_alt: Home - Find answers about Coronavirus (COVID-19) from the CDC.
email: contact@example.gov
description: >- # this means to ignore newlines until "baseurl:"
  CDC works 24/7 to protect America from health, safety and security threats
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://example.gov" # the base hostname & protocol for your site, e.g. http://example.com

# Twitter handle. Only the handle, not the URL.
twitter: CDCgov

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-????????-??


dap_agency: HHS
# USAID   - Agency for International Development
# USDA    - Department of Agriculture
# DOC     - Department of Commerce
# DOD     - Department of Defense
# ED      - Department of Education
# DOE     - Department of Energy
# HHS     - Department of Health and Human Services
# DHS     - Department of Homeland Security
# HUD     - Department of Housing and Urban Development
# DOJ     - Department of Justice
# DOL     - Department of Labor
# DOS     - Department of State
# DOI     - Department of the Interior
# TREAS   - Department of the Treasury
# DOT     - Department of Transportation
# VA      - Department of Veterans Affairs
# EPA     - Environmental Protection Agency
# EOP     - Executive Office of the President
# GSA     - General Services Administration
# NASA    - National Aeronautics and Space Administration
# NARA    - National Archives and Records Administration
# NSF     - National Science Foundation
# NRC     - Nuclear Regulatory Commission
# OPM     - Office of Personnel Management
# USPS    - Postal Service
# SBA     - Small Business Administration
# SSA     - Social Security Administration

#Site internationalization
i18n:
  - language: simplified chinese
    lang: zh
    link: 
    display_text: 中文
  - language: spanish
    lang: es
    link: 
    display_text: Español

# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: Blog
    url: /blog/
  - name: Document
    url: /document/
  - name: Document with sidenav
    url: /document-with-sidenav/
  - name: Document submenu
    children:
      - name: Navigation link
        url: "#main-content"
      - name: Navigation link
        url: "#main-content"
      - name: Navigation link
        url: "#main-content"

secondary_navigation:
  - name: Secondary link
    url: "#main-content"
  - name: Another secondary link
    url: "#main-content"

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:
  endpoint: https://search.usa.gov # You should not change this.
  affiliate: 18fcvddev # replace this with your search.gov account
  access_key: yBQhiqQjR80tDwx5HuPvbluq4NgkO_RTwludGJAPgwg= # This is placeholder. Not private.
  inline: true #this renders the results on the same domain. Otherwise, it will render the results in the search.gov domain

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: false
  categories:
    output: true
    permalink: /:name/
  content:
    output: true
    permalink: /:categories/:name/

defaults:
  -
    scope:
      path: ""
    values:
      lang: en

permalink_custom_vars:
  - lang

markdown: kramdown

#TO UPDATE BEFORE LAUNCH:
url: https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - admin/_config.yml
  - admin/_content_collection_template.yml
  - Dockerfile
  - docker-compose.yml

# CSS and JS assets are compiled by gulp and placed in the intermediary
# output directory _site_assets for use by jekyll-assets
assets:
  sources:
    - _assets/images/icons
    - node_modules/uswds/dist/img
    - node_modules/uswds/dist/js
    - node_modules/uswds/dist/scss
    - node_modules/netlify-cms/dist
    - node_modules
