version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/.jekyll-cache/  # do not sync to host fs for performance reasons
      - /app/_site/          # do not sync to host fs for performance reasons
      - /app/_site_assets/   # do not sync to host fs for performance reasons
