version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
            - v2-npm-
      - run: npm install
      - save_cache:
          key: v2-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - restore_cache:
          keys:
            - v2-bundle-{{ checksum "Gemfile.lock" }}
            - v2-bundle-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v2-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
            - vendor/bundle
            - _site

  test-htmlproofer:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers-legacy
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: bundle config --local path vendor/bundle
      - run: npm run test:htmlproofer

  test-jest:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers-legacy
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run test:jest

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test-htmlproofer:
          requires: [build]
      - test-jest:
          requires: [build]
