version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
            - v2-npm-
      - run: npm install
      - save_cache:
          key: v2-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - restore_cache:
          keys:
            - v2-bundle-{{ checksum "Gemfile.lock" }}
            - v2-bundle-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v2-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: npm run build
      - run: npm run test


workflows:
  version: 2
  commit:
    jobs:
      - build
