backend:
  name: github
  repo: 18f/cv_faq
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: dev #this will need to be changed once we deploy
  use_graphql: true

media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://faq-coronavirus.gov/assets/images/cdc-logo.svg

collections:
  - label: Categories
    name: categories
    folder: _categories/
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'category'}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
  - label: Content
    name: content
    folder: _content/
    create: true
    slug: "{{slug}}"
    fields:
    - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
    - {label: "Title", name: "title", widget: "string"}
    - {
        label: "Publish Date",
        name: "date",
        widget: "datetime",
        format: 'MMMM D, YYYY',
        dateFormat: 'MMMM D, YYYY',
        timeFormat: false
      }
    - {label: "Body", name: "body", widget: "markdown"}



