backend:
  name: github
  repo: 18f/cv_faq
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: netlify-cms-test #this will need to be changed once we deploy
  use_graphql: true

media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://faq-coronavirus.gov/assets/images/cdc-logo.svg

collections:
  - label: Categories
    name: categories
    folder: _categories/
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'category'}
      - {label: 'Name', name: 'name', widget: 'string'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Show on homepage', name: 'promoted', widget: "boolean", default: false}
      - label: 'Banner'
        name: 'banner'
        widget: 'object'
        fields:
            - {label: 'Display', name: 'display', widget: 'boolean', default: false}
            - {label: 'Heading', name: 'heading', widget: 'string'}
            - {label: 'Content', name: 'content', widget: 'text'}
